rewrite lsarchive

diff --git a/lsarchive b/lsarchive
--- a/lsarchive
+++ b/lsarchive
@@ -1,61 +1,50 @@
+#!/usr/bin/env zsh
 #
 # Lists the contents of archives.
 #
 # Authors:
 #   Sorin Ionescu <sorin.ionescu@gmail.com>
-#
+#   Roman Perepelitsa <roman.perepelitsa@gmail.com>
 
-# function lsarchive {
+emulate -L zsh -o no_aliases -o no_unset -o err_return -o pipe_fail
 
-local verbose
-
-if (( $# == 0 )); then
-  cat >&2 <<EOF
-usage: $0 [-option] [file ...]
-
-options:
-    -v, --verbose    verbose archive listing
-
-Report bugs to <sorin.ionescu@gmail.com>.
-EOF
-fi
-
-if [[ "$1" == "-v" || "$1" == "--verbose" ]]; then
-  verbose=0
-  shift
-fi
-
-while (( $# > 0 )); do
-  if [[ ! -s "$1" ]]; then
-    print "$0: file not valid: $1" >&2
-    shift
-    continue
-  fi
-
-  case "$1:l" in
-    (*.tar.gz|*.tgz) tar t${verbose:+v}vzf "$1" ;;
-    (*.tar.bz2|*.tbz|*.tbz2) tar t${verbose:+v}jf "$1" ;;
-    (*.tar.xz|*.txz) tar --xz --help &> /dev/null \
-      && tar --xz -t${verbose:+v}f "$1" \
-      || xzcat "$1" | tar t${verbose:+v}f - ;;
-    (*.tar.zma|*.tlz) tar --lzma --help &> /dev/null \
-      && tar --lzma -t${verbose:+v}f "$1" \
-      || lzcat "$1" | tar x${verbose:+v}f - ;;
-    (*.tar) tar t${verbose:+v}f "$1" ;;
-    (*.zip|*.jar) unzip -l${verbose:+v} "$1" ;;
-    (*.rar) ( (( $+commands[unrar] )) \
-      && unrar ${${verbose:+v}:-l} "$1" ) \
-      || ( (( $+commands[rar] )) \
-      && rar ${${verbose:+v}:-l} "$1" ) \
-      || lsar ${verbose:+-l} "$1" ;;
-    (*.7z) 7za l "$1" ;;
-    (*)
-      print "$0: cannot list: $1" >&2
-      success=1
+local v OPTIND OPTARG
+while getopts ":hv" opt; do
+  case $opt in
+    v)  v=v;;
+    +v) v=;;
+    \?) echo -E - "lsarchive: invalid option: $OPTARG" >&2;            return 1;;
+    :)  echo -E - "lsarchive: missing required argument: $OPTARG" >&2; return 1;;
+    *h)
+      >&2 echo -E - 'usage: lsarchive [{+|-}v] [archive...]'
+      >&2 echo -E - ''
+      >&2 echo -E - 'options:'
+      >&2 echo -E - '    -v    verbose archive listing'
+      return 0
     ;;
   esac
-
-  shift
 done
 
-# }
+local archive
+for archive in "${@:$OPTIND}"; do
+  case ${archive:l} in
+    *.tar.gz|*.tgz)
+      tar tzf$v $archive;;
+    *.tar.bz2|*.tbz|*.tbz2)
+      tar tjf$v $archive;;
+    *.tar.xz|*.txz)
+      tar --xz --help &>/dev/null && tar --xz -tf$v $archive || xzcat $archive | tar tf$v -;;
+    *.tar.lzma|*.tlz)
+      tar --lzma --help &> /dev/null && tar --lzma -tf$v $archive || lzcat $archive | tar xf$v -;;
+    *.tar)
+      tar tf$v $archive;;
+    *.zip|*.jar)
+      unzip -l$v $archive;;
+    *.rar)
+      ${commands[unrar]:-${commands[rar]:-false}} ${v:-l} $archive || lsar ${v:+-l} $archive;;
+    *.7z)
+      7za l $archive;;
+    *)
+      echo -E - "lsarchive: unsupported archive type: ${(q+)archive}."; return 1;;
+  esac
+done
