rewrite unarchive

diff --git a/unarchive b/unarchive
--- a/unarchive
+++ b/unarchive
@@ -1,108 +1,82 @@
+#!/usr/bin/env zsh
 #
 # Extracts the contents of archives.
 #
 # Authors:
 #   Sorin Ionescu <sorin.ionescu@gmail.com>
-#
+#   Roman Perepelitsa <roman.perepelitsa@gmail.com>
 
-# function unarchive {
+emulate -L zsh -o no_aliases -o no_unset -o err_return
 
-local remove_archive
-local success
-local file_name
-local file_path
-local extract_dir
-local _gzip_bin _bzip2_bin _xz_bin
-
-if (( $# == 0 )); then
-  cat >&2 <<EOF
-usage: $0 [-option] [file ...]
-
-options:
-    -r, --remove    remove archive
-
-Report bugs to <sorin.ionescu@gmail.com>.
-EOF
-fi
-
-remove_archive=1
-if [[ "$1" == "-r" || "$1" == "--remove" ]]; then
-  remove_archive=0
-  shift
-fi
-
-# here, we check for dropin/multi-threaded replacements
-# this should eventually be moved to modules/archive/init.zsh
-# as a global alias
-if (( $+commands[pigz] )); then
-  _gzip_bin='pigz'
-else
-  _gzip_bin='gzip'
-fi
-
-if (( $+commands[pixz] )); then
-  _xz_bin='pixz'
-else
-  _xz_bin='xz'
-fi
-
-if (( $+commands[lbzip2] )); then
-  _bzip2_bin='lbzip2'
-elif (( $+commands[pbzip2] )); then
-  _bzip2_bin='pbzip2'
-else
-  _bzip2_bin='bzip2'
-fi
-
-while (( $# > 0 )); do
-  if [[ ! -s "$1" ]]; then
-    print "$0: file not valid: $1" >&2
-    shift
-    continue
-  fi
-
-  success=0
-  file_name="${1:t}"
-  file_path="${1:A}"
-  extract_dir="${file_name:r}"
-  case "$1:l" in
-    (*.tar.gz|*.tgz) tar -xvf "$1" --use-compress-program="${_gzip_bin}" ;;
-    (*.tar.bz2|*.tbz|*.tbz2) tar -xvf "$1" --use-compress-program="${_bzip2_bin}" ;;
-    (*.tar.xz|*.txz) tar -xvf "$1" --use-compress-program="${_xz_bin}" ;;
-    (*.tar.zma|*.tlz) tar --lzma --help &> /dev/null \
-      && tar --lzma -xvf "$1" \
-      || lzcat "$1" | tar -xvf - ;;
-    (*.tar) tar -xvf "$1" ;;
-    (*.gz) gunzip "$1" ;;
-    (*.bz2) bunzip2 "$1" ;;
-    (*.xz) unxz "$1" ;;
-    (*.lzma) unlzma "$1" ;;
-    (*.Z) uncompress "$1" ;;
-    (*.zip|*.jar) unzip "$1" -d $extract_dir ;;
-    (*.rar) ( (( $+commands[unrar] )) \
-      && unrar x -ad "$1" ) \
-      || ( (( $+commands[rar] )) \
-      && rar x -ad "$1" ) \
-      || unar -d "$1" ;;
-    (*.7z) 7za x "$1" ;;
-    (*.deb)
-      mkdir -p "$extract_dir/control"
-      mkdir -p "$extract_dir/data"
-      cd "$extract_dir"; ar vx "${file_path}" > /dev/null
-      cd control; tar xvf ../control.tar.*
-      cd ../data; tar xvf ../data.tar.*
-      cd ..; rm control.tar.* data.tar.* debian-binary
-      cd ..
-    ;;
-    (*)
-      print "$0: cannot extract: $1" >&2
-      success=1
-    ;;
+local remove_archive=0 OPTIND OPTARG
+while getopts ":hr" opt; do
+  case $opt in
+    r)  remove_archive=1;;
+    +r) remove_archive=0;;
+    \?) echo -E - "unarchive: invalid option: $OPTARG" >&2;            return 1;;
+    :)  echo -E - "unarchive: missing required argument: $OPTARG" >&2; return 1;;
+    *h)
+      >&2 echo -E - 'usage: unarchive [{+|-}r] [archive...]'
+      >&2 echo -E - ''
+      >&2 echo -E - 'options:'
+      >&2 echo -E - '    -v    remove archive'
+      return 0
+   ;;
   esac
-
-  (( success = $success > 0 ? $success : $? ))
-  (( $success == 0 )) && (( $remove_archive == 0 )) && rm "$1"
-  shift
 done
 
-# }
+local gzip=${commands[pigz]:-gzip}
+local xz=${commands[pixz]:-xz}
+local bzip2=${commands[lbzip2]:-${commands[pbzip2]:-bzip2}}
+
+local archive
+for archive in "${@:$OPTIND}"; do
+  case $archive in
+    *.tar.gz|*.tgz)
+      tar -xvf $archive --use-compress-program=$gzip;;
+    *.tar.bz2|*.tbz|*.tbz2)
+      tar -xvf $archive --use-compress-program=$bzip2;;
+    *.tar.xz|*.txz)
+      tar -xvf $archive --use-compress-program=$xz;;
+    *.tar.lzma|*.tlz)
+      tar --lzma --help &>/dev/null && tar --lzma -xvf $archive || lzcat $archive | tar -xvf -;;
+    *.tar)
+      tar -xvf $archive;;
+    *.gz)
+      gunzip $archive;;
+    *.bz2)
+      bunzip2 $archive;;
+    *.xz)
+      unxz $archive;;
+    *.lzma)
+      unlzma $archive;;
+    *.Z)
+      uncompress $archive;;
+    *.zip|*.jar)
+      unzip $archive -d ${archive:t:r};;
+    *.rar)
+      ${commands[unrar]:-rar} x -ad $archive
+    *.7z)
+      7za x $archive;;
+    *.deb)
+      (
+        archive=${archive:A}
+        mkdir -p ${archive:t:r}/control
+        mkdir -p ${archive:t:r}/data
+        cd ${archive:t:r}
+        ar vx $archive >/dev/null
+        cd control
+        tar xvf ../control.tar.*
+        cd ../data
+        tar xvf ../data.tar.*
+        cd ..
+        rm control.tar.* data.tar.* debian-binary
+      )
+    ;;
+    *)
+      echo -E - "unarchive: unsupported archive type: ${(q+)archive}."
+      return 1
+    ;;
+  esac
+  (( !remove_archive )) || rm $archive
+done
